export default class {
    static InitialSetup = 'InitialSetup';
    static AuthMng = 'AuthMng';
        static LoginTab = 'LoginTab';
        static SignUpTab = 'SignUpTab';
        static ForgotTab = 'ForgotTab';
        static OtpTab = 'OtpTab';
        static TermsTab = 'TermsTab';
    static App = 'App';
        static Notifications = 'Notifications';
        static Calendar = 'Calendar';
        static DataPages = 'DataPages';
            static HotPicks = 'HotPicks';
            static Cinema = 'Cinema';
            static Attraction = 'Attraction';
            static Travel = 'Travel';
            static Shopping = 'Shopping';
            static Dining = 'Dining';
            static HealthBeauty = 'HealthBeauty';
        static Bookmarks = 'Bookmarks';
        static VirtualReality = 'VirtualReality';
}
