export default {
  SIGN_OUT: 'SIGN_OUT',
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  SELECT_SUBREDDIT : 'SELECT_SUBREDDIT',
  INVALIDATE_SUBREDDIT : 'USER_INVALIDATE',
  REQUEST_POSTS : 'USER_REQUEST',
  RECEIVE_POSTS : 'USER_RECEIVE',
};
