export default {
  SIGN_OUT: 'SIGN_OUT',
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  SELECT_SUBREDDIT : 'SELECT_SUBREDDIT',
  INVALIDATE_SUBREDDIT : 'INVALIDATE_KEY',
  REQUEST_POSTS : 'REQUEST_KEY',
  RECEIVE_POSTS : 'RECEIVE_KEY',
};
