export default class {
  static IS_LOADING = 'CATEGORIES_IS_LOADING';
  static HAS_ERRORED = 'CATEGORIES_HAS_ERRORED';
  static SET_CUR_CATEGORY = 'SET_CUR_CATEGORY';
  static UPDATE_DATA = 'CATEGORIES_UPDATE_DATA';
}
