export default class {
  static HAS_ERRORED = 'CATEGORIES_HAS_ERRORED';
  static SET_CUR_CATEGORY = 'SET_CUR_CATEGORY';
  static UPDATE_DATA = 'CATEGORIES_UPDATE_DATA';
  static UPDATE_FILTER = 'CATEGORIES_UPDATE_FILTER';
  static UPDATE_FILTERS_SETTINGS = 'UPDATE_FILTERS_SETTINGS';
}
